/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import DAO.Conexion;
import Vista.VentanaLogin;
import Vista.VentanaFactura; 
import Vista.VentanaLogin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EZQ
 */
public class VentanaCompra extends javax.swing.JFrame {
VentanaLogin vlogin = new VentanaLogin ();
    /** Creates new form VentanaCompra */
    public VentanaCompra() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxPlatos = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPltSelec = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSubTot = new javax.swing.JTextField();
        btnConfCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTemp = new javax.swing.JTable();
        txtDesc = new javax.swing.JTextField();
        txtTot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel1.setText("ESCOJA LOS PLATOS DESEADOS");

        cbxPlatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorías", "Platos fuertes", "Entradas", "Postres" }));
        cbxPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlatosActionPerformed(evt);
            }
        });

        btnVolver.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha2.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tblPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Platillo", "Precio", "Disponibles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlatos);

        jLabel2.setText("Platillo seleccionado");

        jLabel3.setText("Precio");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Subtotal");

        btnConfCompra.setText("CONFIRMAR COMPRA");
        btnConfCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfCompraActionPerformed(evt);
            }
        });

        tblTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Cliente", "Apellido Cliente", "Platillo", "Precio", "Cantidad", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTemp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(cbxPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSubTot, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(txtPltSelec)
                                            .addComponent(txtPrecio)
                                            .addComponent(txtCant))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTot, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(txtDesc))
                                        .addGap(157, 157, 157)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnConfCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPltSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtSubTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfCompra)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(173, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
        
        vlogin.setVisible(true);
        vlogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbxPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlatosActionPerformed
        // TODO add your handling code here:
        String plt = (String) cbxPlatos.getSelectedItem();
        JOptionPane.showMessageDialog(null, "De clic sobre la fila que tiene el platillo deseado");
        if ("Platos fuertes".equals(plt)) {
            ResultSet res;
            DefaultTableModel modelo = (DefaultTableModel) tblPlatos.getModel();
            modelo.setRowCount(0);
            res = Conexion.Consulta("select NomProd,PrecioProd, StockProd from PRODUCTOS where CategoriaProd=1 ");
            // boolean match = false;
            try {

                while (res.next()) {
                    Vector v = new Vector();
                    v.add(res.getString(1));
                    v.add(res.getDouble(2));
                    v.add(res.getInt(3));
                    modelo.addRow(v);
                    tblPlatos.setModel(modelo);

                }

            } catch (SQLException ex) {
                Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else if ("Entradas".equals(plt)){
             ResultSet res;
            DefaultTableModel modelo = (DefaultTableModel) tblPlatos.getModel();
            modelo.setRowCount(0);
            res = Conexion.Consulta("select NomProd,PrecioProd, StockProd from PRODUCTOS where CategoriaProd=2 ");
            // boolean match = false;
            try {

                while (res.next()) {
                    Vector v = new Vector();
                    v.add(res.getString(1));
                    v.add(res.getDouble(2));
                    v.add(res.getInt(3));
                    
                    modelo.addRow(v);
                    tblPlatos.setModel(modelo);

                }

            } catch (SQLException ex) {
                Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if ("Postres".equals(plt)){
            ResultSet res;
            DefaultTableModel modelo = (DefaultTableModel) tblPlatos.getModel();
            modelo.setRowCount(0);
            res = Conexion.Consulta("select NomProd,PrecioProd, StockProd from PRODUCTOS where CategoriaProd=3 ");
            // boolean match = false;
            try {

                while (res.next()) {
                    Vector v = new Vector();
                    v.add(res.getString(1));
                    v.add(res.getDouble(2));
                    v.add(res.getInt(3));
                    modelo.addRow(v);
                    tblPlatos.setModel(modelo);

                }

            } catch (SQLException ex) {
                Logger.getLogger(VentanaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_cbxPlatosActionPerformed
    int aux=0;
    private void tblPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlatosMouseClicked
        // TODO add your handling code here:
        
        int fila= tblPlatos.getSelectedRow();
        if(fila<0){
            JOptionPane.showMessageDialog(null, "De clic sobre la fila que tiene el platillo deseado");
        }
        else{
            //Tomando los valores de la fila seleccionada
            String platillo = tblPlatos.getValueAt(fila, 0).toString();
            double prec = (double) tblPlatos.getValueAt(fila, 1);
            String precio = String.valueOf(prec);
            int exist = (int) tblPlatos.getValueAt(fila, 2);
            String existencias = String.valueOf(exist);
            int unidad = 1; 
            int resta = exist-unidad; 
            aux= aux+unidad;
            String cant = String.valueOf(aux);  
            tblPlatos.setValueAt(resta, fila, 2);
            double sub = prec*aux ; 
            String subtot = String.valueOf(sub); 
            double descuento = prec * 0.1;
            String d = String.valueOf(descuento);
            double total = sub - descuento;
            String t = String.valueOf(total);
            //Pasando lo obtenido a textfields
            txtPltSelec.setText(platillo);
            txtPrecio.setText(precio);
            txtCant.setText(cant);
            txtSubTot.setText(subtot);
            txtDesc.setText(d);
            txtTot.setText(t); 
            
        }
    }//GEN-LAST:event_tblPlatosMouseClicked
Connection con = null;
int cont=20; 
    private void btnConfCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfCompraActionPerformed
        // TODO add your handling code here:
    cont=cont+1;
    
    try {
        PreparedStatement pps;
        System.out.println(txtPrecio.getText());
        pps = con.prepareStatement("INSERT INTO FACTURA(CodFactura,PrecioUnit, Cantidad, TotalFact, Descuento, APagar)VALUES(?,?,?,?,?,?)");
        pps.setInt(1, cont);
        pps.setDouble(2,Double.parseDouble(txtPrecio.getText()));
        pps.setInt(3,Integer.parseInt(txtCant.getText()));
        pps.setDouble(4,Double.parseDouble(txtSubTot.getText()));
        pps.setDouble(5,Double.parseDouble(txtDesc.getText()));
        pps.setDouble(6,Double.parseDouble(txtTot.getText()));
        JOptionPane.showMessageDialog(null, "Datos guardados");
        int res= pps.executeUpdate();
        if(res<0){
            JOptionPane.showMessageDialog(null, "Error al ingresar");
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(VentanaCompra.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnConfCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfCompra;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxPlatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlatos;
    private javax.swing.JTable tblTemp;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPltSelec;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubTot;
    private javax.swing.JTextField txtTot;
    // End of variables declaration//GEN-END:variables

}
